=== iqb-specifications/acp-scale-derived/acp-scale-derived.schema.json
{
  "$id": "acp-scale-derived@0.4",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Assessment Content Package: Derived Scale",
  "description": "Specification for assessment content package scale: Derived.",
  "type": "object",
  "properties": {
    "id": {
      "description": "Identifier referred by other scales and assessment output.",
      "type": "string",
      "examples": ["bs2004.ma.9.global", "bs2024.ma.9.3", "fcr.de.reading"]
    },
    "name": {
      "$ref": "#/$defs/languageTaggedText"
    },
    "description": {
      "$ref": "#/$defs/languageTaggedText"
    },
    "sources": {
      "description": "List of all scales providing it's value to this scale",
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "method": {
      "description": "Way how to process the scale values.",
      "type": "string",
      "enum": [
        "SUM",
        "MEAN",
        "MAP"
      ],
      "default": "MAP"
    },
    "publicVocabularyUrl": {
      "description": "Url of a public vocabulary matching this scale.",
      "type": "string"
    },
    "mappings": {
      "description": "Applies the method MAP to the value. The first match will go.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "method": {
            "type": "string",
            "description": "Condition for evaluation",
            "enum": [
              "EQUALS",
              "LESS_THAN",
              "MORE_THAN",
              "MAX",
              "MIN"
            ]
          },
          "parameters": {
            "type": "array",
            "description": "Depending on the method, additional parameter(s) is needed.",
            "items": {
              "type": "string"
            }
          },
          "newValue": {
            "$ref": "#/$defs/newValue"
          }
        },
        "required": [
          "method",
          "parameters",
          "newValue"
        ],
        "additionalProperties": false
      }
    },
    "mappingsElse": {
      "$ref": "#/$defs/newValue"
    }
  },
  "required": [
    "id",
    "name",
    "sources"
  ],
  "additionalProperties": false,
  "$defs": {
    "languageTaggedText": {
      "description": "Language tagged text",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "lang": {
            "description": "ISO-language code",
            "type": "string",
            "minLength": 1,
            "pattern": "^[a-z]{2}$"
          },
          "value": {
            "type": "string"
          }
        },
        "required": [
          "lang",
          "value"
        ],
        "additionalProperties": false
      },
      "minItems": 1
    },
    "newValue": {
      "description": "Properties for the new value for scaleType DERIVED",
      "type": "object",
      "properties": {
        "value": {
          "description": "Value as outcome of this scale",
          "type": "number"
        },
        "label": {
          "$ref": "#/$defs/languageTaggedText"
        },
        "description": {
          "$ref": "#/$defs/languageTaggedText"
        },
        "publicVocabularyEntry": {
          "description": "Url-suffix for a specific entry of a public vocabulary.",
          "type": "string"
        }
      },
      "required": [
        "value"
      ],
      "additionalProperties": false
    }
  }
}

=== iqb-specifications/acp-scale-derived/test/DERIVED_2.json
{
  "id": "derived2.comp-level",
  "name": [
    {
      "lang": "de",
      "value": "Kompetenzstufen Ma-P-GM"
    }
  ],
  "description": [
    {
      "lang": "de",
      "value": "Demo-Skala zur Ableitung einer Kompetenzstufe für das Fach Mathematik Primarstufe Globalmodell."
    }
  ],
  "method": "MAP",
  "sources": [
    "base2.wle"
  ],
  "publicVocabularyUrl": "https://w3id.org/iqb/v71/mp1/",
  "mappings": [
    {
      "method": "MIN",
      "parameters": [
        "600"
      ],
      "newValue": {
        "value": 5,
        "label": [
          {
            "lang": "de",
            "value": "Stufe V"
          }
        ],
        "description": [
          {
            "lang": "de",
            "value": "Modellierung komplexer Probleme unter selbstständiger Entwicklung geeigneter Strategien"
          }
        ],
        "publicVocabularyEntry": "p2p"
      }
    },
    {
      "method": "MIN",
      "parameters": [
        "530"
      ],
      "newValue": {
        "value": 4,
        "label": [
          {
            "lang": "de",
            "value": "Stufe IV"
          }
        ],
        "description": [
          {
            "lang": "de",
            "value": "sicheres und flexibles Anwenden von begrifflichem Wissen und Prozeduren im curricularen Umfang"
          }
        ],
        "publicVocabularyEntry": "c2q"
      }
    },
    {
      "method": "MIN",
      "parameters": [
        "460"
      ],
      "newValue": {
        "value": 3,
        "label": [
          {
            "lang": "de",
            "value": "Stufe III"
          }
        ],
        "description": [
          {
            "lang": "de",
            "value": "einfache Anwendungen von Grundlagenwissen (Routineprozeduren in einem klar strukturierten Kontext)"
          }
        ],
        "publicVocabularyEntry": "a5v"
      }
    },
    {
      "method": "MIN",
      "parameters": [
        "390"
      ],
      "newValue": {
        "value": 2,
        "label": [
          {
            "lang": "de",
            "value": "Stufe II"
          }
        ],
        "description": [
          {
            "lang": "de",
            "value": "einfache Anwendungen von Grundlagenwissen (Routineprozeduren in einem klar strukturierten Kontext)"
          }
        ],
        "publicVocabularyEntry": "e3y"
      }
    }
  ],
  "mappingsElse": {
    "value": 1,
    "label": [
      {
        "lang": "de",
        "value": "Stufe I"
      }
    ],
    "description": [
      {
        "lang": "de",
        "value": "technische Grundlagen (Routineprozeduren auf Grundlage einfachen begrifflichen Wissens)"
      }
    ],
    "publicVocabularyEntry": "a9d"
  }
}

=== iqb-specifications/acp-scale-derived/test/DERIVED_1.json
{
  "id": "derived1.percent-ranking",
  "name": [
    {
      "lang": "de",
      "value": "Prozentrang"
    }
  ],
  "description": [
    {
      "lang": "de",
      "value": "Demo-Skala zur Ableitung eines Prozentranges."
    }
  ],
  "method": "MAP",
  "sources": [
    "base1.fcr"
  ],
  "mappings": [
    {
      "method": "MIN",
      "parameters": [
        "75"
      ],
      "newValue": {
        "value": 80,
        "label": [
          {
            "lang": "de",
            "value": "Beste Leistung"
          }
        ]
      }
    },
    {
      "method": "MIN",
      "parameters": [
        "50"
      ],
      "newValue": {
        "value": 65,
        "label": [
          {
            "lang": "de",
            "value": "Gute Leistung"
          }
        ]
      }
    },
    {
      "method": "MIN",
      "parameters": [
        "25"
      ],
      "newValue": {
        "value": 45,
        "label": [
          {
            "lang": "de",
            "value": "Akzeptable Leistung"
          }
        ]
      }
    }
  ],
  "mappingsElse": {
    "value": 0,
    "label": [
      {
        "lang": "de",
        "value": "Nicht ausreichend"
      }
    ]
  }
}

=== iqb-specifications/acp-scale-derived/test/AGGREGATED.json
{
  "id": "aggregated.sum-global",
  "name": [
    {
      "lang": "de",
      "value": "Summieren von Subskalen"
    }
  ],
  "description": [
    {
      "lang": "de",
      "value": "Demo-Skala für das Summieren der Itemsummen aus Subskalen zu einem globalen Skalenwert."
    }
  ],
  "method": "SUM",
  "sources": [
    "fcs.subscale1",
    "fcs.subscale2",
    "fcs.subscale3"
  ]
}
